const Page = {
  getHome: () => '/',
  getLogin: () => '/auth/login',
  getForgot: () => '/forgot',
  getSignup: () => '/signup',
  getVerify: () => '/verify',
  getEditProfile: () => '/edit-profile',
  getUserProfilePage: () => '/user/me',
  getSettings: () => '/settings',
  getDashboard: () => '/dashboard',
  getLogout: () => '',
  getProfile: () => '/user-profile',
  getAdminBlog: () => '/admin/blogs',
  getAdminNotifications: () => '/admin/notifications',
  getAdminSettings: () => '/admin/settings',
  getAdminProfileUpdate: () => '/admin/update-profile',
  getAdminUserManagement: () => '/admin/update-profile',
  getAdminPasswordUpdate: () => '/admin/update-password',
  getAdminLogs: () => '/admin/update-profile',
  getAdminPreferences: () => '/admin/update-profile',
  getAdminSignup: () => '/auth/adminSignup',
  getAdminStore: () => '/admin/stores',
};
export default Page;
