const Page = {
  getHome: () => '/',
  getLogin: () => '/auth/login',
  getForgot: () => '/forgot',
  getSignup: () => '/signup',
  getVerify: () => '/verify',
  getAddress: () => '/shop/users/address',
  getBilling: () => '/shop/users/billing',
  getMyOrder: () => '/shop/users/my-order',
  getReturnItems: () => '/shop/users/return-items',
  getSettings: () => '/shop/users/settings',
  getUserProfilePage: () => '/user/me',
  getUserAddress: () => '/shop/users/address',
  getUpdatePassword: () => '/shop/users/update-password',
  getLogout: () => '',
  getDeleteAccount: () => '/shop/users/deactivation',
  getAdminBlog: () => '/admin/blogs',
  getAdminNotifications: () => '/admin/notifications',
  getAdminSettings: () => '/admin/settings',
  getAdminProfileUpdate: () => '/admin/update-profile',
  getAdminUserManagement: () => '/admin/update-profile',
  getAdminPasswordUpdate: () => '/admin/update-password',
  getAdminLogs: () => '/admin/update-profile',
  getAdminPreferences: () => '/admin/update-profile',
  getAdminSignup: () => '/auth/adminSignup',
  getAdminStore: () => '/admin/stores',
};
export default Page;
